version: 2

models:
  - name: FEATURES
    description: Contains user-level events enriched with a 'feature' label. Features are dynamically determined based on logic stored in the FEATURES JSON from the DATA_SETTINGS table.
    columns:
      - name: TIMESTAMP
        description: Time of the user event.
        tests:
          - not_null

      - name: EVENT
        description: Name of the event triggered by the user.
        tests:
          - not_null

      - name: ACCOUNT_ID
        description: Unique identifier for the account associated with the event.
        tests:
          - not_null

      - name: USER_ID
        description: User ID related to the event.
        tests: []

      - name: FEATURE
        description: Name of the feature this event matched with (based on the JSON rules).
        tests:
          - not_null